import { pool } from '../db';

export const createPtaServicoSocialRepository = async (data: any) => {
  const {
    paciente_id,
    medico_id,
    alta_id,
  mora_sozinho,
  mora_conjuge,
  mora_filho,
  mora_nora_genro,
  mora_irmao,
  mora_institucionalizado,
  mora_outros_text,
  posalta_sozinho,
  posalta_conjuge,
  posalta_filho,
  posalta_nora_genro,
  posalta_irmao,
  posalta_institucionalizado,
  posalta_outros_text,
  familiar_responsavel,
  familiar_telefone,
  renda_aposentadoria,
  renda_bolsa_familia,
  renda_pensao,
  renda_bpc,
  renda_salario,
  renda_outros_text,
  acao_orientacao,
  acao_negligencia,
  acao_encaminhamento_rede,
  acao_outros,
  acao_encaminhamento_outros_text,
    dados_iniciais,
    dados_internacao,
    informacao_alta,
    tipo_orientacao,
    descricao_orientacao,
    orientado_paciente,
    orientado_familiar,
    orientado_cuidador,
    orientado_outros,
    orientado_outros_descricao,
    data_criacao,
  } = data;

  const result = await pool.query(
    `INSERT INTO pta_servicosocial (
      paciente_id, medico_id, alta_id, criado_em,
      mora_sozinho, mora_conjuge, mora_filho, mora_nora_genro, mora_irmao, mora_institucionalizado, mora_outros_text,
      posalta_sozinho, posalta_conjuge, posalta_filho, posalta_nora_genro, posalta_irmao, posalta_institucionalizado, posalta_outros_text,
      familiar_responsavel, familiar_telefone,
      renda_aposentadoria, renda_bolsa_familia, renda_pensao, renda_bpc, renda_salario, renda_outros_text,
      acao_orientacao, acao_negligencia, acao_encaminhamento_rede, acao_outros, acao_encaminhamento_outros_text,
      dados_iniciais, dados_internacao, informacao_alta,
      tipo_orientacao, descricao_orientacao,
      orientado_paciente, orientado_familiar, orientado_cuidador, orientado_outros, orientado_outros_descricao
    ) VALUES (
      $1,$2,$3,$4,
      $5,$6,$7,$8,$9,$10,$11,
      $12,$13,$14,$15,$16,$17,$18,
      $19,$20,
      $21,$22,$23,$24,$25,$26,
      $27,$28,$29,$30,$31,
      $32,$33,$34,
      $35,$36,
      $37,$38,$39,$40,$41
    ) RETURNING *`,
    [
      paciente_id ?? null,
      medico_id ?? null,
      alta_id ?? null,
      data_criacao ?? new Date(),
      mora_sozinho ? 1 : 0,
      mora_conjuge ? 1 : 0,
      mora_filho ? 1 : 0,
      mora_nora_genro ? 1 : 0,
      mora_irmao ? 1 : 0,
      mora_institucionalizado ? 1 : 0,
      mora_outros_text ?? null,
      posalta_sozinho ? 1 : 0,
      posalta_conjuge ? 1 : 0,
      posalta_filho ? 1 : 0,
      posalta_nora_genro ? 1 : 0,
      posalta_irmao ? 1 : 0,
      posalta_institucionalizado ? 1 : 0,
      posalta_outros_text ?? null,
      familiar_responsavel ?? null,
      familiar_telefone ?? null,
      renda_aposentadoria ? 1 : 0,
      renda_bolsa_familia ? 1 : 0,
      renda_pensao ? 1 : 0,
      renda_bpc ? 1 : 0,
      renda_salario ? 1 : 0,
      renda_outros_text ?? null,
      acao_orientacao ? 1 : 0,
      acao_negligencia ? 1 : 0,
      acao_encaminhamento_rede ? 1 : 0,
      acao_outros ? 1 : 0,
      acao_encaminhamento_outros_text ?? null,
      dados_iniciais ?? null,
      dados_internacao ?? null,
      informacao_alta ?? null,
      tipo_orientacao ?? null,
      descricao_orientacao ?? null,
      orientado_paciente ? 1 : 0,
      orientado_familiar ? 1 : 0,
      orientado_cuidador ? 1 : 0,
      orientado_outros ? 1 : 0,
      orientado_outros_descricao ?? null,
    ]
  );

  return result.rows[0];
};

export const getPtaServicoSocialByIdRepository = async (id: number) => {
  const result = await pool.query(`SELECT * FROM pta_servicosocial WHERE id = $1`, [id]);
  return result.rows[0] ?? null;
};
